id = "mercury:confirm_profile_creation"
name = "<dark_green><!italic><bold><translation:inventory.profile.create.confirm_name>"
description = "<!italic><green><translation:inventory.profile.create.confirm_description>"
base_material = "lime_dye"
