# Item configuration file for "test_item"

id = "mercury:test_item"
name = "<dark_red><!italic><bold><translation:item.name.test_item>"
description = "<!italic><red><translation:item.description.test_item>"
base_material = "diamond_sword"
rarity = "unique"

[attributes]
damage = 10
movement_speed = {value = 0.2, operation="MULTIPLY_BASE"}
max_health = {value = -0.2, operation="MULTIPLY_BASE"}
attack_speed = {value = 0.2, operation="MULTIPLY_BASE"}
