name: MercuryCore
version: ${version}
main: me.adamix.mercury.core.MercuryCorePlugin
description: Mercury plugin for core functionality
authors: ["AdamIx"]
api-version: 1.21
commands:
    test: {}
    mercury_reload: {}
    translation: {}
    menu: {}